export enum LexerTokenType {
  ImplicationOp = 'implication_op',
  ReplaceOp = 'replace_op',
  RelOp = 'rel_op',
  OrWord = 'or_word',
  AndWord = 'and_word',
  NotWord = 'not_word',
  LeftPara = 'left_para',
  RightPara = 'right_para',
  PlusOp = 'plus_op',
  MinusOp = 'minus_op',
  MulOp = 'mul_op',
  ListSep = 'list_sep',
  DivOp = 'div_op',
  ModOp = 'mod_op',
  ReturnId = 'return_id',
  LeftArrayBracket = 'left_array_bracket',
  RightArrayBracket = 'right_array_bracket',
  LeftReplaceBracket = 'left_replace_bracket',
  RightReplaceBracket = 'right_replace_bracket',
  ArrayId = 'array_id',
  ArrayIdAux = 'array_id_aux',
  Id = 'id',
  IdAux = 'id_aux',
  Integer = 'integer',
  Ws = 'ws',
}
