export enum ParserNodeType {
  Id = 'id',
  IdAux = 'id_aux',
  Integer = 'integer',
  RelOp = 'rel_op',
  BoolBinaryOp = 'bool_bin_op',
  RelExp = 'rel_exp',
  MathOp = 'math_op',
  BoolUnaryOp = 'bool_un_op',
  Root = 'root',
  FunctionCall = 'function_call',
  ReturnId = 'return_id',
  Array = 'array',
  ArrayId = 'array_id',
  ArrayIdAux = 'array_id_aux',
}
